### ISSUE TITLE
consider casting the numeric parameters to numbers by using param*1 or Number(param)

### ISSUE THREAD

**Issue by sktguha** [Njerschow/openai-api#1]
Consider converting the numeric params as max_tokens etc to numbers. When I was sending "100" for examples, as max_tokens, the API resulted in an error. Various cases where this may happen is if we are passing along user input directly etc
For ex
https://github.com/Njerschow/openai-api/blob/ff691c79028378c0d7003b5beea5d30d2db6924c/index.js#L21

**Comment by Njerschow** [comment]
@sktguha Can you review this PR: #3

**Comment by sktguha** [comment]
Sure. Looks good!
