### ISSUE TITLE
Mismatch between property names in example and the ones expected by `_send_request()` method

### ISSUE THREAD

**Issue by vedtam** [Njerschow/openai-api#10]
Hi,

Noticed that: `best_of `, `presence_penalty` and `frequency_penalty` weren't showing up in the request object when submitting the prompt.
The example uses snake cased property names while the `_send_request()` method expects a camel cased version of the above three properties.  

After changing the casing to camel in the example everything was ok, just wanted to let the author know about this typo.

Regards!

**Comment by rdoyle99** [comment]
Second this, just came to the repo to share my exact same experience!

**Comment by Njerschow** [comment]
Thanks for letting me know @vedtam - Working on a fix and will update here
