### ISSUE TITLE
Providing training data set

### ISSUE THREAD

**Issue by mayur-gaikwad7474** [Njerschow/openai-api#15]
How can i give the training data set ? which is accepted for only first time then we can only pass prompt to the api which will help to save the tokens

**Comment by ankush981** [comment]
@mayur-gaikwad7474 I think this library handles only the completion and search APIs. If you check the unit tests, they've also been written for only these two APIs. If you ask me, you don't need to rely on SDKs as all we need to do is make basic HTTP calls (there are curl examples in the playgorund); but that aside, I think that's all this library does at the moment.

**Comment by Njerschow** [comment]
Hey @mayur-gaikwad7474, @ankush981 is correct. Currently this package only handles the completion and search api calls. Feel free to submit a PR with additional functionality if you think there is something missing.
