### ISSUE TITLE
Extending the docs with an example response

### ISSUE THREAD

**Issue by bausano** [Njerschow/openai-api#17]
It'd be great to add an example successful `response.data` to the README.md.

**Comment by bausano** [comment]
```javascript
{
    id: 'some-long-id',
    object: 'text_completion',
    created: 1616791508,
    model: 'davinci:2020-05-03',
    choices: [
        {
          text: " predicted text...",
          index: 0,
          logprobs: null,
          finish_reason: 'length'
        }
    ]
}
```

**Comment by bausano** [comment]
Alternatively, it'd be great to provide a link to the [documentation](https://beta.openai.com/docs/api-reference/completions/create) and explain that the data object shown in the docs is equal to the data in the docs.

**Comment by Njerschow** [comment]
Noted, thanks!

**Comment by Njerschow** [comment]
added in v1.0.18
