### ISSUE TITLE
Node 14+

### ISSUE THREAD

**Issue by jnorris441** [Njerschow/openai-api#20]
tokenizers@0.7.0 currently only works for node >=10 < 11 || >=12 <14

https://github.com/huggingface/tokenizers/issues/541

People on later versions of node can't use your library unfortunately. This is the OpenAI client I like but I had to swap it for something else.

**Comment by jameswilsterman** [comment]
Having this same issue with Node 12.20.0 actually

**Comment by Mindgames** [comment]
![image](https://user-images.githubusercontent.com/2171273/113448885-f7996900-93fc-11eb-86db-8ee854e4df97.png)

**Comment by mrtncthrn** [comment]
> tokenizers@0.7.0 currently only works for node >=10 < 11 || >=12 <14
> 
> [huggingface/tokenizers#541](https://github.com/huggingface/tokenizers/issues/541)
> 
> People on later versions of node can't use your library unfortunately. This is the OpenAI client I like but I had to swap it for something else.

what package are you using instead?

**Comment by JensLembke** [comment]
Same for me :( node 15.14.0

**Comment by mrtncthrn** [comment]
any update on resolving this issue?

**Comment by JoeyBertschler** [comment]
Has anyone gotten this to run? Perhaps with a different version?
I tried ```nvm use 10.13``` (windows) but to no avail. Details in new issue

**Comment by Njerschow** [comment]
Fixed by #22
