### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by JoeyBertschler** [Njerschow/openai-api#21]
Source:
https://harishgarg.com/writing/how-to-build-a-serverless-gpt-3-powered-using-nextjs-react/

Suspected core Issues (full log below):
-> Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v88-win32-x64-unknown.tar.gz
-> Unsupported engine for tokenizers@0.7.0: wanted: {"node":">=10 < 11 || >=12 <14"} (current: {"node":"14.16.0","npm":"6.14.11"})
-> npm ERR! Failed at the tokenizers@0.7.0 install script. This is probably not a problem with npm. There is likely additional logging output above.

Attempts (windows):
-> nvm use 10.13
failed
-> npm install node-pre-gyp prior
failed
-> npm --build-from-source install bcrypt
failed

Full error log (VSC/ Windows10 64x):
------------------------------------------------------------------
PS C:\Users\j\Desktop\gpt3app\gpt-3-app> npm i openai-api
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> tokenizers@0.7.0 install C:\Users\j\Desktop\gpt3app\gpt-3-app\node_modules\tokenizers
> node-pre-gyp install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v88-win32-x64-unknown.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (C:\Users\j\Desktop\gpt3app\gpt-3-app\node_modules\tokenizers\node_modules\node-pre-gyp\lib\install.js:142:27)
node-pre-gyp ERR! stack     at PassThrough.emit (node:events:381:22)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\j\Desktop\gpt3app\gpt-3-app\node_modules\needle\lib\needle.js:508:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (node:events:476:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:369:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:646:27)   
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:512:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:369:20)
node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:313:12)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Users\\j\\Desktop\\gpt3app\\gpt-3-app\\node_modules\\node\\bin\\node.exe" "C:\\Users\\j\\Desktop\\gpt3app\\gpt-3-app\\node_modules\\tokenizers\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install"
node-pre-gyp ERR! cwd C:\Users\j\Desktop\gpt3app\gpt-3-app\node_modules\tokenizers
node-pre-gyp ERR! node -v v15.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v88-win32-x64-unknown.tar.gz
npm WARN notsup Unsupported engine for tokenizers@0.7.0: wanted: {"node":">=10 < 11 || >=12 <14"} (current: {"node":"14.16.0","npm":"6.14.11"})
npm WARN notsup Not compatible with your version of node/npm: tokenizers@0.7.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tokenizers@0.7.0 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tokenizers@0.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j\AppData\Roaming\npm-cache\_logs\2021-04-21T05_47_51_510Z-debug.log
PS C:\Users\j\Desktop\gpt3app\gpt-3-app>

**Comment by Njerschow** [comment]
Fixed by #22
