### ISSUE TITLE
User field in completions

### ISSUE THREAD

**Issue by adriancsbna** [Njerschow/openai-api#26]
Hello.

I need to use your plugin, but when using the API for a Public Chatbot, OpenAI forces me to send a String field called "user", in which I have to send the user Id.

Could you add that field?

_Edit_
I am also forced to use the content filter, which uses the engine "content-filter-alpha-c4" Could you add it too?

Best regards

**Comment by Njerschow** [comment]
See #29 for updates on the content filter engine

**Comment by Njerschow** [comment]
Can you explain the issue further? Sounds like you need to send a string field named "user" - can you point to the openAI documentation where this is described?

**Comment by Njerschow** [comment]
Resolved by #27
