### ISSUE TITLE
How to handle error for openai.answers

### ISSUE THREAD

**Issue by SprintsAndSneakers** [Njerschow/openai-api#30]
For the search module (openai.answers) I can't find out how to cope with errors.

The error message that pops up has this at the end:
    data: {
      error: {
        code: null,
        message: "No similar documents were found in file with ID 'file-KAPTlH2AyKZGJF8nL1uhYnYE'.Please upload more documents or adjust your query.",
        param: null,
        type: 'invalid_request_error'
      }
    }

If anyone can help me find out where to look.

**Comment by Njerschow** [comment]
This looks like something related to the underlying api rather than this package, I would ask this in the OpenAI community forum.

Closing this issue but feel free to re-open if my assessment is incorrect.
