### ISSUE TITLE
Question/Feature Request: Using Content Filter

### ISSUE THREAD

**Issue by bagelsandgranola** [Njerschow/openai-api#34]
Hello!

Thanks for making this module it's helped me get my OpenAI bot up and running. 

Looking into applying for production and am seeing that their guidelines recommend using the content filter. Is there a way to call that in node?

Here is their reference information which includes how to do it in Python: https://beta.openai.com/docs/engines/content-filter

**Comment by adewandaru** [comment]
The content filter engine's already added, you just have to point to that.
'content-filter-alpha-c4'
