### ISSUE TITLE
How to use streams?

### ISSUE THREAD

**Issue by sabetAI** [Njerschow/openai-api#35]
If I set the `stream` parameter to `true`, how do I read from it and display it in real-time? The only methods available for me to hook into are `then`/`catch`/`finally`, wouldn't an `on` method help in this case?

**Comment by sabetAI** [comment]
Anyone?

**Comment by Njerschow** [comment]
Streams aren't natively supported by this package. I would suggest to ask the community here: https://community.openai.com/
