### ISSUE TITLE
Allow custom `engine`

### ISSUE THREAD

**Issue by tjhorner** [Njerschow/openai-api#36]
Since the fine-tuning endpoints are out, the `engine` can be an arbitrary string. This library should either use the [engines](https://beta.openai.com/docs/api-reference/engines) endpoint to determine the list of available engines (rather than hardcoding them) or just allow any arbitrary string for an engine.

**Comment by Njerschow** [comment]
Thanks, I will open a PR to fix this.

**Comment by rdoyle99** [comment]
seconding this! let me know how I can help

**Comment by Njerschow** [comment]
Fixed in v1.2.5
