### ISSUE TITLE
Content Filter Endpoint

### ISSUE THREAD

**Issue by mrandrewjbaker** [Njerschow/openai-api#9]
I was wondering if it is possible to use the content filter with the complete function?

https://beta.openai.com/docs/content-filter
According to the documentation, you should be able to just reference the engine and set the options, see example.

Example;
```
contentFilter: async function(prompt){
            let gpt3_options = {
                prompt: prompt,
                engine: 'content-filter-alpha-c4',
                maxTokens: 1,
                temperature: 0.0,
                topP: 0

            }

            let gpt3_repsonse = await openai.complete(gpt3_options)
            return await gpt3_response
}
```

Error;
```
UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
```

**Comment by mrandrewjbaker** [comment]
Nevermind, all works as supposed to. I was referencing the wrong function.

**Comment by manish-10** [comment]
can you post the solution? I am facing the same issue.
